### ISSUE TITLE
Program message widget

### ISSUE THREAD

**Issue by larshelge** [dhis2/tracker-capture-app#9] opened 2016-08-04 11:37 UTC
Add a new messaging widget. It should:

- Select the contact information directly from the tracked entity attributes (profile).
- Allow for selecting between sending over SMS and email (when available).
- Allow for entering phone number or email directly.

This widget should use the program message Web API resource.

http://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_program_messages.html

**Comment by abyot** [comment] 2016-09-02 10:08
@larshelge  is this a duplicate of #13

**Comment by jijukjose** [comment] 2016-09-14 08:28
This is implemented as part of - https://github.com/dhis2/tracker-capture-app/issues/13

**Closed by jijukjose** 2016-09-14 08:28 UTC
Labels: enhancement
